### PR TITLE
Update for class indents

### PR DESCRIPTION
**Pull request by carymrobbins**
I recommend that we indent class parameters **2 spaces** as opposed to 4.  Also some other tweaks to class definition style.

### CODE REVIEW

**Comment by yangnirinny** [comment]
Looks good to me.

**Comment by logicbomb** [comment]
The thing that is nice about the 4 spaces is that it provides a visual separation between the parameter list and the method body, if they are all indented with 2 spaces you can't immediately see where the implementation begins.

**Comment by logicbomb** [comment]
What if we indent 2 spaces, and then ensure the return type is on the following line not indented, this provides the visual separation of function signature and implementation:

```
def func(
  foo: String,
  bar: String,
  quux: String )( implicit waz: Int)
: Boolean = {
  println("first line of method body")
}
```

**Comment by carymrobbins** [comment]
@logicbomb - It seems clear to me because of the gap created by the close paren, as well as the initial empty line in the class body -

``` scala
sealed case class Foo(
  a: Int,
  b: Int
) extends Bar {

  def foo(): String = { .. }
}
```

**Comment by carymrobbins** [comment]
@logicbomb 

> What if we indent 2 spaces, and then ensure the return type is on the following line not indented, this provides the visual separation of function signature and implementation:

This is specifically for classes, not functions.

**Comment by logicbomb** [comment]
nevermind me, i got it now, it's fine

**Pull request merged**
